name: baby_development_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # As dependências do projeto
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.1
  hive_flutter: ^1.1.0
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.18
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/logo.png
  
    